### ISSUE TITLE
URL field limited to 200 chars

### ISSUE THREAD

**Issue by AdamLeonSmith** [abe-101/mergecal#125]
(Thanks for creating this great app!)

The ICS URL field is limited to 200 chars, but I have multiple use cases where I need to add a passphrase to the URL and this pushes it over that limit.

I can see that there is no limit in models.py, perhaps is just a UI constraint?

Thanks!

**Comment by abe-101** [comment]
It's using the default django URL model field char limit which is 200

See https://docs.djangoproject.com/en/5.0/ref/models/fields/#urlfield


Feel free to open a PR and declare a larger limit

**Comment by AdamLeonSmith** [comment]
I created and tested a PR locally. It's working for me now.

The PR is failing checks due to files I haven't changed...
