### ISSUE TITLE
Feature request: Prepend Calendar name to events

### ISSUE THREAD

**Issue by SteveChenDC** [abe-101/mergecal#58]
_This is a specific use case for a multi-city iCal subscriptions with similar named events_  
  
Currently, under Gcal Agenda view, there is no way for folks to determine which groups are under a specific city at first glance. I've been informing groups to add the city name to the Meetup EVENT Name to work around this. Groups like Baltimore now do other event formats and prefer not to repeat "Baltimore" again in their Meetup Event Name.

**Current(Agenda view):**

<img width="1650" alt="Screenshot 2023-02-20 at 6 47 49 PM" src="https://user-images.githubusercontent.com/10738004/220214396-2f960f1d-86c4-4d3f-a8f0-5530f33cb54d.png">

**Is it feasible to add a feature to prepend**(or have a toggle for the option) to have the /calendar Name fields ahead of the events? 

Output would look like: `"(CITY): 2022 Retrospective - What went well, what could go better? (online)"`

**Comment by abe-101** [comment]
@SteveChenDC This is definitely possible to implement.

**Comment by abe-101** [comment]
Question / Clarification?

I imagine this feature being a toggle button that when toggled on would prepend the feeds name to each event.

Now my question would you want the option to toggle on a granular level as in a button for each feed
or a toggle for the whole calendar which would toggle it for all of its feeds?

**Comment by chmac** [comment]
Any update on this? It's exactly the feature I'm looking for! We're running a small community project and would like everyone to be able to publish their plans into a single calendar, and then combine all of those into a "group" calendar. But it'd be great to be able to see the names of the people as part of the event. Without that it'll be hard to track who is actually going to be where.

**Comment by abe-101** [comment]
Hey @chmac 
I will work on this over the weekend

Heres how I'm thinking to do it:
add a settings button  to each calendar which leads to a new page where you can change the settings of the calendar
On that page allow you to toggle the request feature:
when toggle on all of this calendar events will look like `(<remote_calendar_name>): <event_title>`

**Comment by abe-101** [comment]
#123 completes the backend changes
